### PR TITLE
ClassPathUtil optimization, closes #4

### LINKED ISSUE #4: Scanning every class is a bad idea/pattern
Loading every class returned by ClassPath.getTopLevelClasses() is a bad idea, as it could take a very long time based on the environment it's executed in.

For example:
https://github.com/UnAfraid/Plugins/blob/d4b6ee5fb57f3a1cef57f576f677c6ef3113362f/Plugins-DB/src/main/java/com/github/unafraid/plugins/db/DatabaseProvider.java#L41
https://github.com/UnAfraid/Plugins/blob/3ba17c2bf0482ea7e42a6808bf078a9cbcc2991d/Plugins-API/src/test/java/com/github/unafraid/plugins/ClassPathTest.java#L40
Calls:
https://github.com/UnAfraid/Plugins/blob/0a0b61241384367a4eaaff099adef2a2db27ba4f/Plugins-API/src/main/java/com/github/unafraid/plugins/util/ClassPathUtil.java#L79-L85
https://github.com/UnAfraid/Plugins/blob/0a0b61241384367a4eaaff099adef2a2db27ba4f/Plugins-API/src/main/java/com/github/unafraid/plugins/util/ClassPathUtil.java#L125-L131
Calls:
https://github.com/UnAfraid/Plugins/blob/76e341224be94230ebf39ddf6d67b3fa5a2f1f4e/Plugins-API/src/main/java/com/github/unafraid/plugins/util/ClassPathUtil.java#L165-L177

It should either use packagePrefix, or service providers.(https://docs.oracle.com/javase/tutorial/ext/basics/spi.html)

Also ClassPath can be cached without issues. So it should be. (See at unity how).

### PR DESCRIPTION
**Pull request by nbali**
- caching ClassPath objects for performance benefits
- dropped complete classpath scanning methods due to performance considerations
- replaced classpath scanning for DatabaseProvider with service providers
- added support for providing the ClassLoader externally

### CODE REVIEW

**Comment by nbali** [comment]
@UnAfraid ping

also if you merge it, please release a new plugins version

**Comment by nbali** [comment]
@UnAfraid what is the new version number? I can't find it in releases/tags

**Comment by UnAfraid** [comment]
1.0.6
https://oss.sonatype.org/content/repositories/releases/com/github/unafraid/plugins/Plugins-API/

**Comment by nbali** [comment]
Next time tag it here as well 😁

2017. okt. 5. de. 10:18 ezt írta ("Rumen Nikiforov" <
notifications@github.com>):

**Pull request merged**
